### ISSUE TITLE
[Refactoring] Split Creation / Edit flow into its own pages

### ISSUE THREAD

**Issue by GrandSchtroumpf** [bancorprotocol/carbon-app#1204]
Currently the edit & creation flow are only 2 pages. It makes it very difficult to create custom design & logic for each form.

## Goals 
- Simplify behavior specific to each strategy
- Reduce technical debt
- Avoid side effect when adding a new feature
- Keep state on reload
- Share prefilled strategy

## Tasks
- [ ] Token selection should be its own page

- [ ] Split create / deposit / withdraw & edit price into 4 pages per type of strategy :
- `create/overlapping`
- `edit/deposit/overlapping`
- `edit/withdraw/overlapping`
- `edit/price/overlapping`
-> Same for `recurring` and `disposable`

- [ ] Use the search params URL to keep state of the fields

For overlapping :
- marketPrice
- min
- max
- spread
- budget
- anchor

For recurring :
- buy.min
- buy.max
- buy.budget
- sell.min
- sell.max
- sell.budget
-> We can derive limit/range from min/max

For disposable: same are recurring with 
- direction

Extract logic from `useCreateStrategy`: 
- #1223
