### ISSUE TITLE
Trade page

### ISSUE THREAD

**Issue by Yanivshechter1** [bancorprotocol/carbon-app#81]
As a user, I would like to be able to trade my tokens and obtain as much information as possible on strategies on Carbon using the frontend.

## High Level  
Trade page should allow users to trade between existing pairs on Carbon protocol while showing all available orders that are available for this pair.

### Trade flow 
1. User Enters trade page 
2. User selects the token pair he would like to trade
3. User can interact with either "sell" or "buy" trade options 
4. User clicks Buy/Sell token options
5. Confirmation popup -User approves the tokens
6. user confirms approval on wallet
7. user confirms trade on wallet

### Design 
https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?node-id=1849%3A40044&t=QM79HeQq35NaUnaF-4

### Unselected token pair  
-- Trade page behavior before the user chooses the pair he wishes
* Upon entering the trade page, open the token pair selection pop-up 
* If the user clicks "x" and closes the popup without choosing a pair, show an empty state page
-- Design -TBD 

**bonus enhancement**
- store last viewed pair in local storage
- when visiting the page, IF there is a last viewed pair, 
-- [true] open this pair. 
-- [false] open the "unselected token pair" view

## Behavior 
-- Here will be presented all the page components and their explanation this issue has been divided into four parts due to its complexity 

### Token selection

- [x] Token selection flow is explained in #93 

### Trade widget
- [x] Trade widget details are explained in issue #83 
### Order book list
- [x] Order book details are explained in issue #99 
### Depth chart
- [x] Order book details are explained in issue #94 
### Settings
- [ ] user defined settings are explained in issue #116 
### Token approval 
* Once a user clicks the "Buy" / "Sell"  on the #83  form, we would like to follow this process.
-- Token balance>existing approve -> open the popup and let the user trigger the relevant approve.
-- Token.balance<existing approve -> indicate "Pre-approved" (skip the approval popup and trigger the transaction on the connected wallet)
-- ETH special case -> since ETH doesnt require approve, if token is ETH -> indicate "Pre-approve"
* Design - https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?node-id=2375%3A44162&t=U5m8ZuPTBwAgNuvf-4
